const categories = [
  {
    id: "men",
    name: "Men",
    image:
      "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&q=80&w=500",
    description: "Shop sustainable men's fashion",
  },
  {
    id: "women",
    name: "Women",
    image:
      "https://plus.unsplash.com/premium_photo-1690349404224-53f94f20df8f?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Discover eco-friendly women's wear",
  },
  {
    id: "kids",
    name: "Kids",
    image:
      "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Njl8fGtpZHN8ZW58MHx8MHx8fDA%3D",
    description: "Sustainable fashion for little ones",
  },
  {
    id: "beauty",
    name: "Beauty",
    image:
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&q=80&w=500",
    description: "Natural and organic beauty products",
  },
  {
    id: "home-kitchen",
    name: "Home & Kitchen",
    image:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&q=80&w=500",
    description: "Eco-friendly home essentials",
  },
];

const menProducts = [ 

  {
    id: 1,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.meesho.com/images/products/383857316/f4ypd_512.avif?width=512",
    alt: "Men's Classic Shirt",
  },
  {
    id: 2,
    name: "KEESOR Men Tshirt|Men Printed Round neck Tshirt|Men Graphic print Tshirt",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.meesho.com/images/products/503007534/bt8eo_512.avif?width=512",
    alt: "Slim Fit Jeans",
  },
  {
    id: 3,
    name: "MENS OVERSIZE TEES",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.meesho.com/images/products/481484866/xtrjc_512.avif?width=512",
    alt: "Leather Jacket",
  },
  {
    id: 4,
    name: "CHHOTE NAWAB Men's Geometric Regular Polo Teal Tshirts",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.meesho.com/images/products/430702252/uigxu_512.avif?width=512",
    alt: "Casual Sneakers",
  },
  {
    id: 5,
    name: "MEN SELF DESIGN POLO T SHIRT FOR MEN AND BOYS",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.meesho.com/images/products/544486003/lhyv7_512.avif?width=512",
    alt: "Men's Classic Shirt",
  },
  {
    id: 6,
    name: "FOXGLOW Men Fashion Cotton Blend T-Shirt ",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.meesho.com/images/products/563822664/osdem_512.avif?width=512",
    alt: "Slim Fit Jeans",
  },
  {
    id: 7,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.meesho.com/images/products/538291130/ekbjj_512.avif?width=512",
    alt: "Leather Jacket",
  },
  {
    id: 8,
    name: "100% COTTON STYLISH JACKET FOR MEN",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.meesho.com/images/products/541471993/ag17k_512.avif?width=512",
    alt: "Casual Sneakers",
  },
  {
    id: 9,
    name: "Men's Regular Fit Washed Full Sleeve Denim Jacket",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.meesho.com/images/products/541117151/iwy7q_512.avif?width=512",
    alt: "Men's Classic Shirt",
  },
  {
    id: 10,
    name: "Tranding boys men blue pant | non stretchable",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.meesho.com/images/products/542460767/3izor_512.avif?width=512",
    alt: "Slim Fit Jeans",
  },
  {
    id: 11,
    name: "Casual Men Track Pants Combo",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.meesho.com/images/products/122102209/f29yy_512.avif?width=512",
    alt: "Leather Jacket",
  },
  {
    id: 12,
    name: "Stylish Men's Casual Shorts",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.meesho.com/images/products/538637536/ch9kn_512.avif?width=512",
    alt: "Casual Sneakers",
  },
  {
    id: 13,
    name: "Men Denim Slim Fit Stretchable Jeans",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.meesho.com/images/products/229299286/klpbs_512.avif?width=512",
    alt: "Men's Classic Shirt",
  },
  {
    id: 14,
    name: "KIPEKEE Premium Elegant Men Formal Trouser Pant",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.meesho.com/images/products/493792935/dhcwr_512.avif?width=512",
    alt: "Slim Fit Jeans",
  },
  {
    id: 15,
    name: "Stylish Track Pants for Men",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.meesho.com/images/products/497079521/3zaj0_512.avif?width=512",
    alt: "Leather Jacket",
  },
  {
    id: 16,
    name: "Pack of 2 Men Solid Grey, Black Track Pants",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.meesho.com/images/products/544213484/nmoqv_512.avif?width=512",
    alt: "Casual Sneakers",
  },
];
const womenProducts = [
  {
    id: 1,
    name: "Fabfairy Women Viscose Rayon Kurta Pant Dupatta Set",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.meesho.com/images/products/441070939/rzuyp_512.avif?width=512",
    alt: "Women's Classic Shirt",
  },
  {
    id: 2,
    name: "KURTI",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.meesho.com/images/products/191005346/mocgn_512.avif?width=360",
    alt: "Slim Fit Jeans",
  },
  {
    id: 3,
    name: "Rayon Printed Kurta Set With Dupatta",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.meesho.com/images/products/519996287/y5mid_512.avif?width=512",
    alt: "Leather Jacket",
  },
  {
    id: 4,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.meesho.com/images/products/397953982/lq6a2_512.avif?width=512",
    alt: "Casual Sneakers",
  },
];


const KidsProducts = [
  {
    id: 1,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 3,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 4,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 5,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 6,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 7,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 8,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 9,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 10,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 11,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 12,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 13,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 14,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 15,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 16,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
];


const BeautyProducts = [
  {
    id: 1,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 3,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 4,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 5,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 6,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 7,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 8,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 9,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 10,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 11,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 12,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 13,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 14,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 15,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 16,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
];


const Home_KitchenProducts = [
  {
    id: 1,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 3,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 4,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 5,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 6,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 7,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 8,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 9,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 10,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 11,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 12,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
  {
    id: 13,
    name: "Men's Classic Shirt",
    description: "A timeless cotton shirt perfect for formal and casual occasions.",
    price: "$29.99",
    oldPrice: "$50.00",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    alt: "Men's Classic Shirt",
  },
  {
    id: 14,
    name: "Slim Fit Jeans",
    description: "Comfortable and stylish denim jeans for everyday wear.",
    price: "$49.99",
    oldPrice: "$80.00",
    image: "https://images.unsplash.com/photo-1602293589930-45aad59ba90c?auto=format&fit=crop&w=600&q=80",
    alt: "Slim Fit Jeans",
  },
  {
    id: 15,
    name: "Leather Jacket",
    description: "Premium leather jacket for a bold and rugged look.",
    price: "$99.99",
    oldPrice: "$150.00",
    image: "https://images.unsplash.com/photo-1551028719-6e3c8b6b6f9b?auto=format&fit=crop&w=600&q=80",
    alt: "Leather Jacket",
  },
  {
    id: 16,
    name: "Casual Sneakers",
    description: "Versatile sneakers for comfort and style all day long.",
    price: "$59.99",
    oldPrice: "$100.00",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    alt: "Casual Sneakers",
  },
];



export const getLocalStorage = () => {
  const categories = JSON.parse(localStorage.getItem("categories"));
  const menProduct = JSON.parse(localStorage.getItem("MenProducts"));
  const womenProduct = JSON.parse(localStorage.getItem("MenProducts"));
  const kidsProduct = JSON.parse(localStorage.getItem("MenProducts"));
  const beautyProduct = JSON.parse(localStorage.getItem("MenProducts"));
  const homeKitchenProduct = JSON.parse(localStorage.getItem("MenProducts"));
  return { categories, menProduct, womenProduct, kidsProduct, beautyProduct, homeKitchenProduct};
};